"""initial schema: five schemas (identity, health, billing, catalog, admin), every table,
and the append-only trigger on admin.audit_log.

Revision ID: 0001
Revises:
Create Date: 2026-10-04 06:36:06.985750+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import stacksense.db
from stacksense.db import SCHEMAS
from stacksense.modules.admin.models import AUDIT_APPEND_ONLY_PG

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    for schema in SCHEMAS:
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('sso_subject', sa.String(length=128), nullable=True),
    sa.Column('totp_secret_enc', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users')),
    sa.UniqueConstraint('email', name=op.f('uq_admin_users_email')),
    sa.UniqueConstraint('sso_subject', name=op.f('uq_admin_users_sso_subject')),
    schema='admin'
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ts', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    schema='admin'
    )
    op.create_index(op.f('ix_admin_audit_log_action'), 'audit_log', ['action'], unique=False, schema='admin')
    op.create_index(op.f('ix_admin_audit_log_actor'), 'audit_log', ['actor'], unique=False, schema='admin')
    op.create_index(op.f('ix_admin_audit_log_target_id'), 'audit_log', ['target_id'], unique=False, schema='admin')
    op.create_index(op.f('ix_admin_audit_log_ts'), 'audit_log', ['ts'], unique=False, schema='admin')
    op.create_table('job_runs',
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('last_run_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_job_runs')),
    schema='admin'
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=48), nullable=False),
    sa.Column('outcome', sa.String(length=48), nullable=False),
    sa.Column('prompt_hash', sa.String(length=16), nullable=False),
    sa.Column('response_hash', sa.String(length=16), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('ts', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls')),
    schema='admin'
    )
    op.create_index(op.f('ix_admin_llm_calls_job'), 'llm_calls', ['job'], unique=False, schema='admin')
    op.create_index(op.f('ix_admin_llm_calls_ts'), 'llm_calls', ['ts'], unique=False, schema='admin')
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('template', sa.String(length=48), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scheduled_for', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('sent_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_outbox_dedupe_key')),
    schema='admin'
    )
    op.create_index(op.f('ix_admin_outbox_scheduled_for'), 'outbox', ['scheduled_for'], unique=False, schema='admin')
    op.create_index(op.f('ix_admin_outbox_user_id'), 'outbox', ['user_id'], unique=False, schema='admin')
    op.create_table('privacy_requests',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('jurisdiction', sa.String(length=16), nullable=True),
    sa.Column('due_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_privacy_requests')),
    schema='admin'
    )
    op.create_index(op.f('ix_admin_privacy_requests_user_id'), 'privacy_requests', ['user_id'], unique=False, schema='admin')
    op.create_table('releases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('base_version', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('reviewer', sa.String(length=64), nullable=True),
    sa.Column('rollout_pct', sa.Integer(), nullable=False),
    sa.Column('check_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('published_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_releases')),
    schema='admin'
    )
    op.create_index(op.f('ix_admin_releases_version'), 'releases', ['version'], unique=False, schema='admin')
    op.create_table('staff_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.String(length=40), nullable=False),
    sa.Column('admin_role', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('ts', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_access')),
    schema='admin'
    )
    op.create_index(op.f('ix_admin_staff_access_user_id'), 'staff_access', ['user_id'], unique=False, schema='admin')
    op.create_table('billing_plans',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('limits', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_billing_plans')),
    schema='billing'
    )
    op.create_table('checkout_sessions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('plan_key', sa.String(length=32), nullable=False),
    sa.Column('price_id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=True),
    sa.Column('session_id', sa.String(length=40), nullable=True),
    sa.Column('promo_code', sa.String(length=32), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkout_sessions')),
    schema='billing'
    )
    op.create_index(op.f('ix_billing_checkout_sessions_user_id'), 'checkout_sessions', ['user_id'], unique=False, schema='billing')
    op.create_table('entitlements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('feature_key', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('granted_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entitlements')),
    schema='billing'
    )
    op.create_index(op.f('ix_billing_entitlements_user_id'), 'entitlements', ['user_id'], unique=False, schema='billing')
    op.create_table('experiment_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experiment_key', sa.String(length=64), nullable=False),
    sa.Column('subject_key', sa.String(length=64), nullable=False),
    sa.Column('variant', sa.String(length=32), nullable=False),
    sa.Column('assigned_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_assignments')),
    sa.UniqueConstraint('experiment_key', 'subject_key', name=op.f('uq_experiment_assignments_experiment_key')),
    schema='billing'
    )
    op.create_index(op.f('ix_billing_experiment_assignments_experiment_key'), 'experiment_assignments', ['experiment_key'], unique=False, schema='billing')
    op.create_table('experiments',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('surface', sa.String(length=16), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=True),
    sa.Column('variants', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('guardrails', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stop_reason', sa.Text(), nullable=True),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_experiments')),
    schema='billing'
    )
    op.create_table('funnel_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_hash', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=48), nullable=False),
    sa.Column('props', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ts', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funnel_events')),
    schema='billing'
    )
    op.create_index(op.f('ix_billing_funnel_events_actor_hash'), 'funnel_events', ['actor_hash'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_funnel_events_event'), 'funnel_events', ['event'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_funnel_events_ts'), 'funnel_events', ['ts'], unique=False, schema='billing')
    op.create_table('paywall_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('gates', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('triggers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('copy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('published_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paywall_configs')),
    schema='billing'
    )
    op.create_table('promo_codes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('percent_off', sa.Float(), nullable=False),
    sa.Column('plan_keys', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=True),
    sa.Column('partner', sa.String(length=64), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_promo_codes')),
    schema='billing'
    )
    op.create_table('purchases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('plan_key', sa.String(length=32), nullable=False),
    sa.Column('price_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_checkout_id', sa.String(length=80), nullable=True),
    sa.Column('stripe_payment_intent', sa.String(length=80), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=True),
    sa.Column('promo_code', sa.String(length=32), nullable=True),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('refunded_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchases')),
    sa.UniqueConstraint('stripe_checkout_id', name=op.f('uq_purchases_stripe_checkout_id')),
    schema='billing'
    )
    op.create_index(op.f('ix_billing_purchases_stripe_payment_intent'), 'purchases', ['stripe_payment_intent'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_purchases_user_id'), 'purchases', ['user_id'], unique=False, schema='billing')
    op.create_table('stripe_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('received_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stripe_events')),
    schema='billing'
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('plan_key', sa.String(length=32), nullable=False),
    sa.Column('price_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('current_period_end', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('trial_end', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('cancel_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_event_created', sa.Integer(), nullable=False),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('stripe_subscription_id', name=op.f('uq_subscriptions_stripe_subscription_id')),
    schema='billing'
    )
    op.create_index(op.f('ix_billing_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False, schema='billing')
    op.create_table('catalog_snapshots',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_snapshots')),
    schema='catalog'
    )
    op.create_table('clicks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_hash', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=True),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('retailer', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('ts', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clicks')),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_clicks_plan_id'), 'clicks', ['plan_id'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_clicks_product_id'), 'clicks', ['product_id'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_clicks_ts'), 'clicks', ['ts'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_clicks_user_hash'), 'clicks', ['user_hash'], unique=False, schema='catalog')
    op.create_table('conversions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('network_order_id', sa.String(length=80), nullable=False),
    sa.Column('click_id', sa.String(length=40), nullable=True),
    sa.Column('retailer', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('ts', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversions')),
    sa.UniqueConstraint('network_order_id', name=op.f('uq_conversions_network_order_id')),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_conversions_click_id'), 'conversions', ['click_id'], unique=False, schema='catalog')
    op.create_table('link_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('retailer', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('checked_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_link_checks')),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_link_checks_checked_at'), 'link_checks', ['checked_at'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_link_checks_product_id'), 'link_checks', ['product_id'], unique=False, schema='catalog')
    op.create_table('product_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_overrides')),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_product_overrides_product_id'), 'product_overrides', ['product_id'], unique=False, schema='catalog')
    op.create_table('products',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    schema='catalog'
    )
    op.create_table('retailer_programs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retailer_programs')),
    schema='catalog'
    )
    op.create_table('subjects',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('wrapped_dek', sa.Text(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('linked_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    schema='health'
    )
    op.create_table('magic_links',
    sa.Column('jti', sa.String(length=40), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('jti', name=op.f('pk_magic_links')),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_magic_links_email_hash'), 'magic_links', ['email_hash'], unique=False, schema='identity')
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('email_enc', sa.Text(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('tz', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=8), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
    sa.Column('subject_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_users_email_hash'), 'users', ['email_hash'], unique=True, schema='identity')
    op.create_index(op.f('ix_identity_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_users_subject_id'), 'users', ['subject_id'], unique=False, schema='identity')
    op.create_table('prices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_key', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_key'], ['billing.billing_plans.key'], name=op.f('fk_prices_plan_key_billing_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prices')),
    schema='billing'
    )
    op.create_index(op.f('ix_billing_prices_plan_key'), 'prices', ['plan_key'], unique=False, schema='billing')
    op.create_table('calendar_feeds',
    sa.Column('calendar_key', sa.String(length=40), nullable=False),
    sa.Column('subject_id', sa.String(length=40), nullable=False),
    sa.Column('feed_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['health.subjects.id'], name=op.f('fk_calendar_feeds_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('calendar_key', name=op.f('pk_calendar_feeds')),
    schema='health'
    )
    op.create_index(op.f('ix_health_calendar_feeds_subject_id'), 'calendar_feeds', ['subject_id'], unique=False, schema='health')
    op.create_table('intake_sessions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('subject_id', sa.String(length=40), nullable=False),
    sa.Column('graph_version', sa.String(length=40), nullable=False),
    sa.Column('rules_version', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=True),
    sa.Column('state_enc', sa.Text(), nullable=False),
    sa.Column('flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('cards_answered', sa.Integer(), nullable=False),
    sa.Column('branch_events', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('returning_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['health.subjects.id'], name=op.f('fk_intake_sessions_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intake_sessions')),
    schema='health'
    )
    op.create_index(op.f('ix_health_intake_sessions_subject_id'), 'intake_sessions', ['subject_id'], unique=False, schema='health')
    op.create_table('labs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.String(length=40), nullable=False),
    sa.Column('analyte', sa.String(length=32), nullable=False),
    sa.Column('value_enc', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('drawn_at', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['health.subjects.id'], name=op.f('fk_labs_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labs')),
    schema='health'
    )
    op.create_index(op.f('ix_health_labs_subject_id'), 'labs', ['subject_id'], unique=False, schema='health')
    op.create_table('plans',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('subject_id', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=True),
    sa.Column('parent_plan_id', sa.String(length=40), nullable=True),
    sa.Column('rules_version', sa.String(length=40), nullable=False),
    sa.Column('graph_version', sa.String(length=40), nullable=False),
    sa.Column('impact_version', sa.String(length=40), nullable=False),
    sa.Column('catalog_snapshot_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('result_enc', sa.Text(), nullable=False),
    sa.Column('inputs_enc', sa.Text(), nullable=True),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('calendar_key', sa.String(length=40), nullable=False),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['health.subjects.id'], name=op.f('fk_plans_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    schema='health'
    )
    op.create_index(op.f('ix_health_plans_calendar_key'), 'plans', ['calendar_key'], unique=False, schema='health')
    op.create_index(op.f('ix_health_plans_session_id'), 'plans', ['session_id'], unique=False, schema='health')
    op.create_index(op.f('ix_health_plans_subject_id'), 'plans', ['subject_id'], unique=False, schema='health')
    op.create_table('profile_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload_enc', sa.Text(), nullable=False),
    sa.Column('ts', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['health.subjects.id'], name=op.f('fk_profile_events_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_events')),
    schema='health'
    )
    op.create_index(op.f('ix_health_profile_events_subject_id'), 'profile_events', ['subject_id'], unique=False, schema='health')
    op.create_index(op.f('ix_health_profile_events_ts'), 'profile_events', ['ts'], unique=False, schema='health')
    op.create_table('user_features',
    sa.Column('subject_id', sa.String(length=40), nullable=False),
    sa.Column('features_enc', sa.Text(), nullable=False),
    sa.Column('computed_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['health.subjects.id'], name=op.f('fk_user_features_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', name=op.f('pk_user_features')),
    schema='health'
    )
    op.create_table('consents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('ts', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('enforced_at', stacksense.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], name=op.f('fk_consents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents')),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_consents_ts'), 'consents', ['ts'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_consents_user_id'), 'consents', ['user_id'], unique=False, schema='identity')
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('keys', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], name=op.f('fk_push_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscriptions')),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False, schema='identity')
    op.create_table('answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('node_version', sa.Integer(), nullable=False),
    sa.Column('value_enc', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('answered_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['health.intake_sessions.id'], name=op.f('fk_answers_session_id_intake_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers')),
    schema='health'
    )
    op.create_index(op.f('ix_health_answers_session_id'), 'answers', ['session_id'], unique=False, schema='health')
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('payload_enc', sa.Text(), nullable=False),
    sa.Column('created_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['health.plans.id'], name=op.f('fk_checkins_plan_id_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['health.subjects.id'], name=op.f('fk_checkins_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkins')),
    schema='health'
    )
    op.create_index(op.f('ix_health_checkins_plan_id'), 'checkins', ['plan_id'], unique=False, schema='health')
    op.create_index(op.f('ix_health_checkins_subject_id'), 'checkins', ['subject_id'], unique=False, schema='health')
    op.create_table('dose_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=False),
    sa.Column('ingredient_id', sa.String(length=64), nullable=False),
    sa.Column('slot', sa.String(length=16), nullable=False),
    sa.Column('rrule', sa.String(length=255), nullable=False),
    sa.Column('local_time', sa.String(length=5), nullable=False),
    sa.Column('tz', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('uid', sa.String(length=80), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['health.plans.id'], name=op.f('fk_dose_events_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dose_events')),
    schema='health'
    )
    op.create_index(op.f('ix_health_dose_events_plan_id'), 'dose_events', ['plan_id'], unique=False, schema='health')
    op.create_index(op.f('ix_health_dose_events_uid'), 'dose_events', ['uid'], unique=False, schema='health')
    op.create_table('dose_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=False),
    sa.Column('ingredient_id', sa.String(length=64), nullable=False),
    sa.Column('slot', sa.String(length=16), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('logged_at', stacksense.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['health.plans.id'], name=op.f('fk_dose_logs_plan_id_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['health.subjects.id'], name=op.f('fk_dose_logs_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dose_logs')),
    sa.UniqueConstraint('plan_id', 'occurred_on', 'slot', 'ingredient_id', name=op.f('uq_dose_logs_plan_id')),
    schema='health'
    )
    op.create_index(op.f('ix_health_dose_logs_plan_id'), 'dose_logs', ['plan_id'], unique=False, schema='health')
    op.create_index(op.f('ix_health_dose_logs_subject_id'), 'dose_logs', ['subject_id'], unique=False, schema='health')
    op.create_table('plan_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=False),
    sa.Column('ingredient_id', sa.String(length=64), nullable=False),
    sa.Column('form', sa.String(length=32), nullable=True),
    sa.Column('dose', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('reason_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['health.plans.id'], name=op.f('fk_plan_items_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_items')),
    schema='health'
    )
    op.create_index(op.f('ix_health_plan_items_plan_id'), 'plan_items', ['plan_id'], unique=False, schema='health')
    op.create_table('plan_item_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('retailer', sa.String(length=32), nullable=True),
    sa.Column('affiliate_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_item_id'], ['health.plan_items.id'], name=op.f('fk_plan_item_products_plan_item_id_plan_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_item_products')),
    schema='health'
    )
    op.create_index(op.f('ix_health_plan_item_products_plan_item_id'), 'plan_item_products', ['plan_item_id'], unique=False, schema='health')
    # ### end Alembic commands ###
    op.execute(AUDIT_APPEND_ONLY_PG)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_append_only ON admin.audit_log")
    op.execute("DROP FUNCTION IF EXISTS admin.reject_audit_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_plan_item_products_plan_item_id'), table_name='plan_item_products', schema='health')
    op.drop_table('plan_item_products', schema='health')
    op.drop_index(op.f('ix_health_plan_items_plan_id'), table_name='plan_items', schema='health')
    op.drop_table('plan_items', schema='health')
    op.drop_index(op.f('ix_health_dose_logs_subject_id'), table_name='dose_logs', schema='health')
    op.drop_index(op.f('ix_health_dose_logs_plan_id'), table_name='dose_logs', schema='health')
    op.drop_table('dose_logs', schema='health')
    op.drop_index(op.f('ix_health_dose_events_uid'), table_name='dose_events', schema='health')
    op.drop_index(op.f('ix_health_dose_events_plan_id'), table_name='dose_events', schema='health')
    op.drop_table('dose_events', schema='health')
    op.drop_index(op.f('ix_health_checkins_subject_id'), table_name='checkins', schema='health')
    op.drop_index(op.f('ix_health_checkins_plan_id'), table_name='checkins', schema='health')
    op.drop_table('checkins', schema='health')
    op.drop_index(op.f('ix_health_answers_session_id'), table_name='answers', schema='health')
    op.drop_table('answers', schema='health')
    op.drop_index(op.f('ix_identity_push_subscriptions_user_id'), table_name='push_subscriptions', schema='identity')
    op.drop_table('push_subscriptions', schema='identity')
    op.drop_index(op.f('ix_identity_consents_user_id'), table_name='consents', schema='identity')
    op.drop_index(op.f('ix_identity_consents_ts'), table_name='consents', schema='identity')
    op.drop_table('consents', schema='identity')
    op.drop_table('user_features', schema='health')
    op.drop_index(op.f('ix_health_profile_events_ts'), table_name='profile_events', schema='health')
    op.drop_index(op.f('ix_health_profile_events_subject_id'), table_name='profile_events', schema='health')
    op.drop_table('profile_events', schema='health')
    op.drop_index(op.f('ix_health_plans_subject_id'), table_name='plans', schema='health')
    op.drop_index(op.f('ix_health_plans_session_id'), table_name='plans', schema='health')
    op.drop_index(op.f('ix_health_plans_calendar_key'), table_name='plans', schema='health')
    op.drop_table('plans', schema='health')
    op.drop_index(op.f('ix_health_labs_subject_id'), table_name='labs', schema='health')
    op.drop_table('labs', schema='health')
    op.drop_index(op.f('ix_health_intake_sessions_subject_id'), table_name='intake_sessions', schema='health')
    op.drop_table('intake_sessions', schema='health')
    op.drop_index(op.f('ix_health_calendar_feeds_subject_id'), table_name='calendar_feeds', schema='health')
    op.drop_table('calendar_feeds', schema='health')
    op.drop_index(op.f('ix_billing_prices_plan_key'), table_name='prices', schema='billing')
    op.drop_table('prices', schema='billing')
    op.drop_index(op.f('ix_identity_users_subject_id'), table_name='users', schema='identity')
    op.drop_index(op.f('ix_identity_users_stripe_customer_id'), table_name='users', schema='identity')
    op.drop_index(op.f('ix_identity_users_email_hash'), table_name='users', schema='identity')
    op.drop_table('users', schema='identity')
    op.drop_index(op.f('ix_identity_magic_links_email_hash'), table_name='magic_links', schema='identity')
    op.drop_table('magic_links', schema='identity')
    op.drop_table('subjects', schema='health')
    op.drop_table('retailer_programs', schema='catalog')
    op.drop_table('products', schema='catalog')
    op.drop_index(op.f('ix_catalog_product_overrides_product_id'), table_name='product_overrides', schema='catalog')
    op.drop_table('product_overrides', schema='catalog')
    op.drop_index(op.f('ix_catalog_link_checks_product_id'), table_name='link_checks', schema='catalog')
    op.drop_index(op.f('ix_catalog_link_checks_checked_at'), table_name='link_checks', schema='catalog')
    op.drop_table('link_checks', schema='catalog')
    op.drop_index(op.f('ix_catalog_conversions_click_id'), table_name='conversions', schema='catalog')
    op.drop_table('conversions', schema='catalog')
    op.drop_index(op.f('ix_catalog_clicks_user_hash'), table_name='clicks', schema='catalog')
    op.drop_index(op.f('ix_catalog_clicks_ts'), table_name='clicks', schema='catalog')
    op.drop_index(op.f('ix_catalog_clicks_product_id'), table_name='clicks', schema='catalog')
    op.drop_index(op.f('ix_catalog_clicks_plan_id'), table_name='clicks', schema='catalog')
    op.drop_table('clicks', schema='catalog')
    op.drop_table('catalog_snapshots', schema='catalog')
    op.drop_index(op.f('ix_billing_subscriptions_user_id'), table_name='subscriptions', schema='billing')
    op.drop_table('subscriptions', schema='billing')
    op.drop_table('stripe_events', schema='billing')
    op.drop_index(op.f('ix_billing_purchases_user_id'), table_name='purchases', schema='billing')
    op.drop_index(op.f('ix_billing_purchases_stripe_payment_intent'), table_name='purchases', schema='billing')
    op.drop_table('purchases', schema='billing')
    op.drop_table('promo_codes', schema='billing')
    op.drop_table('paywall_configs', schema='billing')
    op.drop_index(op.f('ix_billing_funnel_events_ts'), table_name='funnel_events', schema='billing')
    op.drop_index(op.f('ix_billing_funnel_events_event'), table_name='funnel_events', schema='billing')
    op.drop_index(op.f('ix_billing_funnel_events_actor_hash'), table_name='funnel_events', schema='billing')
    op.drop_table('funnel_events', schema='billing')
    op.drop_table('experiments', schema='billing')
    op.drop_index(op.f('ix_billing_experiment_assignments_experiment_key'), table_name='experiment_assignments', schema='billing')
    op.drop_table('experiment_assignments', schema='billing')
    op.drop_index(op.f('ix_billing_entitlements_user_id'), table_name='entitlements', schema='billing')
    op.drop_table('entitlements', schema='billing')
    op.drop_index(op.f('ix_billing_checkout_sessions_user_id'), table_name='checkout_sessions', schema='billing')
    op.drop_table('checkout_sessions', schema='billing')
    op.drop_table('billing_plans', schema='billing')
    op.drop_index(op.f('ix_admin_staff_access_user_id'), table_name='staff_access', schema='admin')
    op.drop_table('staff_access', schema='admin')
    op.drop_index(op.f('ix_admin_releases_version'), table_name='releases', schema='admin')
    op.drop_table('releases', schema='admin')
    op.drop_index(op.f('ix_admin_privacy_requests_user_id'), table_name='privacy_requests', schema='admin')
    op.drop_table('privacy_requests', schema='admin')
    op.drop_index(op.f('ix_admin_outbox_user_id'), table_name='outbox', schema='admin')
    op.drop_index(op.f('ix_admin_outbox_scheduled_for'), table_name='outbox', schema='admin')
    op.drop_table('outbox', schema='admin')
    op.drop_index(op.f('ix_admin_llm_calls_ts'), table_name='llm_calls', schema='admin')
    op.drop_index(op.f('ix_admin_llm_calls_job'), table_name='llm_calls', schema='admin')
    op.drop_table('llm_calls', schema='admin')
    op.drop_table('job_runs', schema='admin')
    op.drop_index(op.f('ix_admin_audit_log_ts'), table_name='audit_log', schema='admin')
    op.drop_index(op.f('ix_admin_audit_log_target_id'), table_name='audit_log', schema='admin')
    op.drop_index(op.f('ix_admin_audit_log_actor'), table_name='audit_log', schema='admin')
    op.drop_index(op.f('ix_admin_audit_log_action'), table_name='audit_log', schema='admin')
    op.drop_table('audit_log', schema='admin')
    op.drop_table('admin_users', schema='admin')
    # ### end Alembic commands ###
    for schema in reversed(SCHEMAS):
        op.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
